name = input("Please enter yout name ")
age = int(input("Please enter your age "))
role = input ("Please enter your role ")
next_year_age= (age+1)
print("---- My Profile ----")
print("Name:", name)
print("Age:", age)
print("Role:", role)
print("Next year you will be", next_year_age)
